Câu 1: Hãy viết chương trình sử dụng hàm zeros tạo Numpy array, Tensorflow tensor, Pytorch tensor chỉ chứa giá trị là số 0 với kích thước (3, 4)?

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [4]:
arr_zeros = np.zeros((3, 4))
print(arr_zeros)

tensor_zeros_pt = torch.zeros((3, 4))
print(tensor_zeros_pt)

tensor_zeros_tf = tf.zeros((3, 4))
print(tensor_zeros_tf)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


Câu 2: Hãy viết chương trình sử dụng hàm ones tạo Numpy array, Tensorflow tensor, Pytorch tensor chỉ chứa giá trị là số 0 với kích thước (3, 4)?

In [5]:
arr_ones = np.ones((3, 4))
print(arr_ones)

tensor_ones_pt = torch.ones((3, 4))
print(tensor_ones_pt)

tensor_ones_tf = tf.ones((3, 4))
print(tensor_ones_tf)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


Câu 3: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor chỉ chứa giá trị là số 5 với kích thước (3, 4)

In [8]:
arr_full_5 = np.full((3, 4), 5)
print(arr_full_5)

tensor_full_5_pt = torch.full((3, 4), 5)
print(tensor_full_5_pt)

tensor_full_5_tf = tf.fill((3, 4), 5)
print(tensor_full_5_tf)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
