## **Câu 1:**  
Viết chương trình tạo hai Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 4). Sau đó chuyển vị array, tensor thứ 2 và thực hiện phép nhân matrix multiplication. Lưu ý: sử dụng seed=2024

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [42]:
# Numpy
np.random.seed(2024)
arr_1 = np.random.randint(-10, 10, (3, 4))
arr_2 = np.random.randint(-10, 10, (3, 4))
print(arr_1)
print(arr_2)

# Pytorch
torch.manual_seed(2024)
tensor_1_pt = torch.randint(-10, 10, (3, 4))
tensor_2_pt = torch.randint(-10, 10, (3, 4))
print(tensor_1_pt)
print(tensor_2_pt)

# Tensorflow
tf.random.set_seed(2024)
tensor_1_tf = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.int32)
tensor_2_tf = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.int32)
print(tensor_1_tf)
print(tensor_2_tf)


[[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
[[ 5  0  4  5]
 [ 1 -3  8 -1]
 [-4  0 -9 -5]]
tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])
tf.Tensor(
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)


In [43]:
# Numpy
arr_2 = np.transpose(arr_2)
#arr_2 = arr_2.T
print(arr_2)

# Pytorch
tensor_2_pt = torch.t(tensor_2_pt)
#tensor_2_pt = torch.transpose(tensor_2_pt, 0, 1)
#tensor_2_pt = tensor_2_pt.T
print(tensor_2_pt)

# Tensorflow
tensor_2_tf = tf.transpose(tensor_2_tf)
print(tensor_2_tf)

[[ 5  1 -4]
 [ 0 -3  0]
 [ 4  8 -9]
 [ 5 -1 -5]]
tensor([[  1,  -9,  -3],
        [  8, -10,  -7],
        [  0,  -9,  -4],
        [ -2,   0,   8]])
tf.Tensor(
[[-3  2  4]
 [-7 -5 -3]
 [ 9 -3 -3]
 [ 3 -5  5]], shape=(4, 3), dtype=int32)


In [44]:
# Numpy
matmul_arr = np.matmul(arr_1, arr_2)
print(matmul_arr)

# Pytorch
matmul_tensor_pt = torch.matmul(tensor_1_pt, tensor_2_pt)
print(matmul_tensor_pt)

# Tensorflow
matmul_tensor_tf = tf.matmul(tensor_1_tf, tensor_2_tf)
print(matmul_tensor_tf)

[[-80 -46 128]
 [-33 -30  67]
 [-25 -25  42]]
tensor([[  22,   36,  -62],
        [ -89,  163,   99],
        [  87, -180, -148]])
tf.Tensor(
[[  26    8  -28]
 [-112    0   46]
 [ -25   28   -6]], shape=(3, 3), dtype=int32)


## **Câu 2:** 
Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 3). Sau đó hãy tính tổng của toàn bộ tensor, array, tiếp theo tính tổng theo chiều dọc, chiều ngang . Lưu ý: sử dụng seed=2024

In [53]:
# Numpy (array)
np.random.seed(2024)
arr_np = np.random.randint(-10, 10, (3, 3))
print(arr_np)
print("Tổng array:", np.sum(arr_np))
print("Tổng array chiều dọc:", np.sum(arr_np, axis=0))
print("Tổng array chiều ngang:", np.sum(arr_np, axis=1))

[[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Tổng array: -53
Tổng array chiều dọc: [-15 -11 -27]
Tổng array chiều ngang: [-22 -16 -15]


In [54]:
# Pytorch (Tensor)
torch.manual_seed(2024)

tensor_pt = torch.randint(-10, 10, (3, 3))
print(tensor_pt)
print("Tổng tensor:", torch.sum(tensor_pt))
print("Tổng tensor chiều dọc:", torch.sum(tensor_pt, axis=0))
print("Tổng tensor chiều ngang:", torch.sum(tensor_pt, axis=1))

tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Tổng tensor: tensor(-27)
Tổng tensor chiều dọc: tensor([ -8,  -6, -13])
Tổng tensor chiều ngang: tensor([ -4, -27,   4])


In [56]:
# Tensorflow (Tensor)
tf.random.set_seed(2024)

tensor_tf = tf.random.uniform((3, 3), minval=-10, maxval=10, dtype=tf.int32)
print(tensor_tf)
print("Tổng tensor:", tf.reduce_sum(tensor_tf))
print("Tổng tensor chiều dọc:", tf.reduce_sum(tensor_tf, axis=0))
print("Tổng tensor chiều ngang:", tf.reduce_sum(tensor_tf, axis=1))

tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
Tổng tensor: tf.Tensor(-1, shape=(), dtype=int32)
Tổng tensor chiều dọc: tf.Tensor([-17   5  11], shape=(3,), dtype=int32)
Tổng tensor chiều ngang: tf.Tensor([-8  6  1], shape=(3,), dtype=int32)
