Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor từ danh sách 1 chiều?

In [1]:
import numpy as np
import torch 
import tensorflow as tf

In [2]:
data_1D = [1, 2, 3]

array_1D = np.array(data_1D)
print(array_1D)

tensor_1D_pt = torch.tensor(data_1D)
print(tensor_1D_pt)

tensor_1D_tf = tf.constant(data_1D)
print(tensor_1D_tf)

[1 2 3]
tensor([1, 2, 3])
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
# Các thư viện có thể chuyển đổi lẫn nhau trong quá trình tính toán
print(tensor_1D_pt @ array_1D)  # Nhân ma trận giữa pytorch và numpy. Đầu ra là một scalar

### Đầu ra của kết quả sẽ theo thứ tự ưu tiên Tensorflow > Pytorch > Numpy
result = tensor_1D_tf - (tensor_1D_pt @ array_1D) * array_1D
print(result)

tensor(14)
tf.Tensor([-13 -26 -39], shape=(3,), dtype=int32)


Câu 2: Hãy viết chương trình tạo Numypy array, Tensorflow tensor, Pytorch tensor từ danh sách 2 chiều. Sau đó thực hiện kiểm tra thuộc tính shape, dtype, type, device từ các array, tensor vừa tạo?

In [15]:
data_2D = [[1, 2, 3], [4, 5, 6]]

array_2D = np.array(data_2D)
print(array_2D)
print("Kich thuoc cua mang numpy: ", array_2D.shape)
print("Kieu du lieu cua numpy: ", array_2D.dtype)
print("Loai cua numpy: ", type(array_2D), end="\n\n")

tensor_2D_pt = torch.tensor(array_2D)
print(tensor_2D_pt)
print("Kich thuoc cua tensor: ", tensor_2D_pt.shape)
print("Kieu du lieu cua tensor: ", tensor_2D_pt.dtype)
print("Loai cua tensor: ", type(tensor_2D_pt))
print("Thiet bi luu tru cua tensor: ", tensor_2D_pt.device, end="\n\n")

tensor_2D_tf = tf.constant(array_2D)
print(tensor_2D_tf)
print("Kich thuoc cua tensor: ", tensor_2D_tf.shape)
print("Kieu du lieu cua tensor: ", tensor_2D_tf.dtype)
print("Loai cua tensor: ", type(tensor_2D_tf))
print("Thiet bi luu tru cua tensor: ", tensor_2D_tf.device)


[[1 2 3]
 [4 5 6]]
Kich thuoc cua mang numpy:  (2, 3)
Kieu du lieu cua numpy:  int32
Loai cua numpy:  <class 'numpy.ndarray'>

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kich thuoc cua tensor:  torch.Size([2, 3])
Kieu du lieu cua tensor:  torch.int32
Loai cua tensor:  <class 'torch.Tensor'>
Thiet bi luu tru cua tensor:  cpu

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Kich thuoc cua tensor:  (2, 3)
Kieu du lieu cua tensor:  <dtype: 'int32'>
Loai cua tensor:  <class 'tensorflow.python.framework.ops.EagerTensor'>
Thiet bi luu tru cua tensor:  /job:localhost/replica:0/task:0/device:CPU:0
